### ISSUE TITLE
All method schemas as a single document

### ISSUE THREAD

**Issue by jayrbolton** [kbaseIncubator/jsonrpcbase#25]
Another approach to associating json-schemas to methods would be to use a single document with definitions and a few naming conventions:

```yaml
title: Service Title
description: Service description

definitions:
    methods:
        get_something:
            params: "schema goes here"
            result: "schema goes here"
    mydef1: "Generic type definition goes here for use in methods"
    mydef2: "Another type definition goes here"
```

pros/cons:
* `+` Entire service can be described in a single document similar to OpenAPI
* `+` Everything conforms to the vanilla json-schema spec
* `+` Very easy to add and reference generic type definitions and can reuse any definition inside another definition
* `-` Have to introduce a few special definition names ("methods", "params", and "result") that would be a specific convention for KBase, not an external standard
* `-` Document may be overly large (could make use of json-schema uri file references)
* `-` Not clear how to include service metadata like version, urls, license
